services:
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    image: mariadb
    environment:
      MDB_ROOT_PASSWORD: ${MDB_ROOT_PASSWORD}
      MDB_USER: ${MDB_USER}
      MDB_PASSWORD: ${MDB_PASSWORD}     
      MDB_DATABASE: ${MDB_DATABASE}
    volumes:
      - mdb_data:/var/lib/mysql
    restart: always
    networks:
      - mpoplow_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u${MDB_USER} -p${MDB_PASSWORD} --silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:rw
    restart: always
    networks:
      - mpoplow_network
    
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    image: wordpress
    environment:
      MDB_ROOT_PASSWORD: ${MDB_ROOT_PASSWORD}
      MDB_USER: ${MDB_USER}
      MDB_PASSWORD: ${MDB_PASSWORD}     
      MDB_DATABASE: ${MDB_DATABASE}
      DBHOST: ${DBHOST}
      WPAD_USER: ${WPAD_USER}
      WPAD_EMAIL: ${WPAD_EMAIL}
      WPAD_PASSWORD: ${WPAD_PASSWORD}
      ZWEIER_PASSWORD: ${ZWEIER_PASSWORD}
    depends_on:
      mariadb:
          condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    restart: always 
    networks:
      - mpoplow_network

volumes:
  mdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpoplow/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpoplow/data/wordpress

networks:
  mpoplow_network: